---
name: github pages
on:
  push:
    branches:
      - main
    paths-ignore: ['paper/**', 'README.md', 'LICENSE.txt']
  pull_request:
    branches:
      - main
    paths-ignore: ['paper/**', 'README.md', 'LICENSE.txt']
jobs:
  make:
    runs-on: ubuntu-latest
    steps:
      - run: mvn clean install
      - run: mkdir gh-pages
      - run: cp -r target/. gh-pages
      - uses: JamesIves/github-pages-deploy-action@v4.4.0
        with:
          branch: gh-pages
          folder: gh-pages
          clean: false
