---
name: pdd
on:
  push:
    branches:
      - main
    paths-ignore: ['paper/**', 'README.md', 'LICENSE.txt']
  pull_request:
    branches:
      - main
    paths-ignore: ['paper/**', 'README.md', 'LICENSE.txt']
jobs:
  pdd:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: g4s8/pdd-action@master
